const topics = [
  "Data Structures",
  "Algorithms",
  "Object-Oriented Programming",
  "Functional Programming",
  "Procedural Programming",
  "Cryptography",
  "Greedy Algorithms",
  "Machine Learning",
  "Artificial Intelligence",
  "Deep Learning",
  "Neural Networks",
  "Computer Vision",
  "Natural Language Processing",
  "Reinforcement Learning",
  "Genetic Algorithms",
  "Operating Systems",
  "Network Programming",
  "Web Development",
  "Mobile Development",
  "Game Development",
  "Database Systems",
  "SQL and NoSQL databases",
  "Cloud Computing",
  "Distributed Systems",
  "Parallel Computing",
  "Cybersecurity",
  "Software Testing",
  "Software Engineering",
  "DevOps",
  "Microservices",
  "API Design",
  "System Design",
  "Compiler Design",
  "Real-Time Systems",
  "Embedded Systems",
  "IoT (Internet of Things)",
  "Augmented Reality",
  "Virtual Reality",
  "Blockchain",
  "Quantum Computing",
  "Graphics Programming",
  "User Interface Design",
  "User Experience Design",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Lean Software Development",
  "Design Patterns",
  "Multithreading and Concurrency",
  "Memory Management",
  "Performance Optimization",
  "Debugging Techniques",
  "Version Control Systems",
  "Open Source Development",
  "Software Licensing",
  "Ethical Hacking",
  "Data Science",
  "Big Data",
  "Data Mining",
  "Data Visualization",
  "Bioinformatics",
  "Computational Physics",
  "High Performance Computing",
  "Digital Signal Processing",
  "Image Processing",
  "Audio Processing",
  "Text Processing",
  "Web Scraping",
  "Automation",
  "Robotics",
  "3D Printing",
  "Computer Hardware",
  "Computer Networking",
  "Wireless Communication",
  "Information Theory",
  "Error Detection and Correction",
  "Compression Algorithms",
  "Cryptocurrency",
  "Digital Forensics",
  "Penetration Testing",
  "Reverse Engineering",
  "Kernel Development",
  "Firmware Development",
  "Human-Computer Interaction",
  "Accessibility in Software",
  "Internationalization and Localization",
  "Software Project Management",
  "Quality Assurance",
  "Continuous Integration/Continuous Deployment",
  "Serverless Architecture",
  "Containerization (Docker, Kubernetes)",
  "Infrastructure as Code",
  "Configuration Management",
  "IT Service Management",
  "IT Governance",
  "IT Risk Management",
  "IT Compliance",
  "Digital Transformation",
  "IT Strategy",
  "IT Operations Management",
];

function getRandomTopic() {
  const randomIndex = Math.floor(Math.random() * topics.length);
  return topics[randomIndex];
}

module.exports = getRandomTopic;
